# Generated by Django 5.0.14 on 2026-05-30 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='academicintegrityreport',
            options={'verbose_name': 'Akademik halollik hisoboti', 'verbose_name_plural': 'Akademik halollik hisobotlari'},
        ),
        migrations.AlterModelOptions(
            name='accesslog',
            options={'verbose_name': 'Kirish jurnali', 'verbose_name_plural': 'Kirish jurnallari'},
        ),
    ]
