# Generated by Django 5.0.14 on 2026-05-30 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answerchoice',
            options={'verbose_name': 'Javob varianti', 'verbose_name_plural': 'Javob variantlari'},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'verbose_name': 'Savol', 'verbose_name_plural': 'Savollar'},
        ),
        migrations.AlterModelOptions(
            name='quiz',
            options={'verbose_name': 'Viktorina', 'verbose_name_plural': 'Viktorinalar'},
        ),
        migrations.AlterModelOptions(
            name='quizattempt',
            options={'verbose_name': 'Viktorina urinishi', 'verbose_name_plural': 'Viktorina urinishlari'},
        ),
    ]
