# Generated by Django 5.0.14 on 2026-05-30 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='portfolio',
            options={'verbose_name': 'Portfolio', 'verbose_name_plural': 'Portfoliolar'},
        ),
        migrations.AlterModelOptions(
            name='projectitem',
            options={'verbose_name': 'Loyiha elementi', 'verbose_name_plural': 'Loyiha elementlari'},
        ),
    ]
