# Generated by Django 5.0.14 on 2026-05-30 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='forumpost',
            options={'verbose_name': 'Forum posti', 'verbose_name_plural': 'Forum postlari'},
        ),
        migrations.AlterModelOptions(
            name='forumthread',
            options={'verbose_name': 'Forum mavzusi', 'verbose_name_plural': 'Forum mavzulari'},
        ),
    ]
