# Generated by Django 5.0.14 on 2026-05-30 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='performancemetric',
            options={'verbose_name': "Samaradorlik ko'rsatkichi", 'verbose_name_plural': "Samaradorlik ko'rsatkichlari"},
        ),
        migrations.AlterModelOptions(
            name='useractivity',
            options={'verbose_name': 'Foydalanuvchi faolligi', 'verbose_name_plural': 'Foydalanuvchi faolliklari'},
        ),
    ]
